[package]
name = "cmzip"
version = "0.1.0"
authors = ["gtomsic"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
xz2 = ">= 0.1"
clap = {version = ">= 2.27.0", features = ["wrap_help"]}